# Generated by Django 5.1.7 on 2025-03-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.FloatField()),
                ('loan_period', models.IntegerField()),
                ('rate_of_interest', models.FloatField()),
                ('total_interest', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('monthly_emi', models.FloatField()),
                ('amount_paid', models.FloatField(default=0)),
                ('emis_paid', models.IntegerField(default=0)),
                ('loan_start_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EMI', 'EMI'), ('LUMP_SUM', 'LUMP_SUM')], max_length=10)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loan')),
            ],
        ),
    ]
